
export class PermissionSettingConfig {
	public genres_permissions = [
		"ADMINS_GENRES_INDEX",
		"ADMINS_GENRES_STORE",
		"ADMINS_GENRES_SHOW",
		"ADMINS_GENRES_UPDATE",
		"ADMINS_GENRES_DESTROY",
	];

	public roles_permissions = [
		"ADMINS_ROLES_INDEX",
		"ADMINS_ROLES_STORE",
		"ADMINS_ROLES_SHOW",
		"ADMINS_ROLES_UPDATE",
		"ADMINS_ROLES_DESTROY",
		"ADMINS_ROLE_EXPORT",
		"ADMINS_PERMISSIONS_LIST",
	];

	public companies_permissions = [
		"ADMINS_COMPANIES_INDEX",
		"ADMINS_COMPANIES_STORE",
		"ADMINS_COMPANIES_SHOW",
		"ADMINS_COMPANIES_UPDATE",
		"ADMINS_COMPANIES_DESTROY",
	];

	public companyTypes_permissions = [
		"ADMINS_COMPANY_TYPES_INDEX",
		"ADMINS_COMPANY_TYPES_STORE",
		"ADMINS_COMPANY_TYPES_SHOW",
		"ADMINS_COMPANY_TYPES_UPDATE",
		"ADMINS_COMPANY_TYPES_DESTROY",
	];

	public crews_permissions = [
		"ADMINS_CREWS_INDEX",
		"ADMINS_CREWS_STORE",
		"ADMINS_CREWS_SHOW",
		"ADMINS_CREWS_UPDATE",
		"ADMINS_CREWS_DESTROY",
	];

	public crewTypes_permissions = [
		"ADMINS_CREW_TYPES_INDEX",
		"ADMINS_CREW_TYPES_STORE",
		"ADMINS_CREW_TYPES_SHOW",
		"ADMINS_CREW_TYPES_UPDATE",
		"ADMINS_CREW_TYPES_DESTROY",
	];

	public nationalities_permissions = [
		"ADMINS_NATIONALITIES_INDEX",
		"ADMINS_NATIONALITIES_STORE",
		"ADMINS_NATIONALITIES_SHOW",
		"ADMINS_NATIONALITIES_UPDATE",
		"ADMINS_NATIONALITIES_DESTROY",
	];

	public users_permissions = [
		"ADMINS_USERS_INDEX",
		"ADMINS_USERS_STORE",
		"ADMINS_USERS_SHOW",
		"ADMINS_USERS_UPDATE",
		"ADMINS_USERS_DESTROY",
	];

	public admins_permissions = [
		"ADMINS_ADMINS_INDEX",
		"ADMINS_ADMINS_STORE",
		"ADMINS_ADMINS_SHOW",
		"ADMINS_ADMINS_UPDATE",
		"ADMINS_ADMINS_DESTROY",
	];

	public clips_permissions = [
		"ADMINS_CLIPS_INDEX",
		"ADMINS_CLIPS_STORE",
		"ADMINS_CLIPS_SHOW",
		"ADMINS_CLIPS_UPDATE",
		"ADMINS_CLIPS_DESTROY",
	];

	public tags_permissions = [
		"ADMINS_TAGS_INDEX",
		"ADMINS_TAGS_STORE",
		"ADMINS_TAGS_SHOW",
		"ADMINS_TAGS_UPDATE",
		"ADMINS_TAGS_DESTROY",
	];
}
